---
name: Test

on:
  workflow_run:
    workflows:
      - Preflight
    types:
      - completed

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: chromaui/action-canary
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        projectToken: 5oy3iw6rkio
        storybookBuildDir: storybook-static
